name: Update README Stars
on:
  schedule:
    - cron: "18 5 * 12,1 *"  # Every day at 6:51 AM
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1527014
          leaderboardId: 972845
          year: 2025
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars